name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Change to "master" if your default branch is "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Django migrations
        run: |
          python backend/manage.py migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies & build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Heroku
        run: |
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/your-heroku-app.git HEAD:main
